V2
crossopt/Roguelike pull request #2
Opened 2020-04-19 20:09 UTC by crossopt

2020-05-06 15:41 UTC, yurii-litvinov commented on src/fighting_system.py
> +            defender.become_confused(CONFUSION_TIME)
Что-то с отступом не то

2020-05-06 16:14 UTC, yurii-litvinov requested changes
В целом по функциональности и по коду всё ок. Но документацию не показывает, fairfeather.tk не ресолвится у меня. Кстати, добавьте на него ссылку куда-нибудь в репозиторий, если это не против ваших идеологических взглядов, а то неудобно искать.

2020-05-06 16:14 UTC, yurii-litvinov commented on src/fighting_system.py
> +            defender.become_confused(CONFUSION_TIME)
Что-то с отступом не то

2020-05-06 16:14 UTC, yurii-litvinov commented on src/strategies.py
> +            if new_distance < current_model.map.get_distance(best_position, player_position):
Так он рискует в стене застрять, по-хорошему надо гнать Дейкстру. Правда, может, так и задумывалось

2020-05-06 16:14 UTC, yurii-litvinov commented on src/controller.py
> +            self.player_died = True
Было бы неплохо говорить, что игрок умер, а то сейчас окно просто внезапно закрывается

2020-05-06 16:14 UTC, yurii-litvinov commented on src/strategies.py
> +class PassiveStrategy(FightingStrategy):
Я правильно понимаю, что PassiveStrategy у реалдьных мобов не применяется? Судя по https://github.com/crossopt/Roguelike/pull/2/files#diff-a052258567465b2bef9e088806cae968R69

2020-05-06 16:21 UTC, ivankrut856 commented on src/strategies.py
> +            if new_distance < current_model.map.get_distance(best_position, player_position):
Если речь о том, что он может в стену _упереться_, то задумывалось, да. А, коллизии не здесь обрабатываются, и там проблем вроде нет

2020-05-06 17:18 UTC, yurii-litvinov commented on src/strategies.py
> +            if new_distance < current_model.map.get_distance(best_position, player_position):
Да, _упереться_ в указанном смысле. Хорошо

2020-05-06 17:20 UTC, yurii-litvinov commented
Коментарии по диздоку к этой версии:
- на диаграмме классов Weapon* канонично писать Weapon [*], если имелась в виду множественность, а не тип-указатель. И в других аналогичных местах.
- ConfusedStrategy и FightingStrategy могли бы быть связаны агрегацией явно, а не атрибутом. Это более наглядно, а так надо вчитываться, чтобы понять, кто про кого знает
- Непонятно, кто вызывает генератор карты, на диаграмме он своей жизнью живёт.
- На диаграмме случаев использования над стрелками с пунктирными линиями надо написать либо `<<extend>>`, либо `<<include>>`. От этого, кстати, зависит направление стрелок (`<<extend>>` указывает на случай, который расширяется другим случаем, `<<include>>` ведёт от того, кто включает в того, кого включают).

В общем, диздок, пожалуйста, немного поправьте, и заодно замечания по коду (сообщение, что игра закончилась и пассивных мобов на карте, если я всё правильно понял). А первая часть задачи теперь зачтена.

2020-05-08 13:17 UTC, yurii-litvinov requested changes
Ещё комментарий по 3-й части задачи: совсем нету тестов на новую функциональность. Неплохо бы проверять, что сохранение действительно сохраняет, что после смерти персонажа сохранение удаляется, что команды делают что нужно и т.д.

2020-06-18 13:30 UTC, merged